using Modele;
using System;
using System.Collections.Generic;
using System.Text;
using Xunit;

namespace TestUnitaires
{
    public class UTManager
    {
        [Fact]
        public void TestConstructeurChargeDonnées()
        {
            Manager Mgr = new Manager(new Stub.Stub());
            Mgr.ChargeDonnees();
            Assert.True(Mgr.Utilisateurs[2].Equals(new Utilisateur("VERDIER", "Nathan", "nathan.jpg", 19, "natahn.VERDIER@gmail.com", "07 63 58 92 10", "Bonjour à tous, je suis friant des voyage et adore cette application :", "Waarx", "Nathan63")));
            //Assert.True(Mgr.Utilisateurs[0].Evenements[new DateTime(12 / 06 / 21)].Equals(new DateTime(12 / 06 / 21)), "Fondu savoyarde");


            Assert.True(Mgr.Regions[1].Equals(new Region("Provence-Alpes-Côte d'Azur", "Provence-Alpes-Côte d'Azur est une région administrative du Sud-Est de la France. Son chef-lieu est Marseille, deuxième ville la plus peuplée de France.Provence-Alpes-Côte d'Azur est formée de six départements issus des anciennes provinces de Provence, du Comté de Nice, du Comtat Venaissin et d'une partie du Dauphiné : les Alpes-de-Haute-Provence, les Hautes-Alpes, les Alpes-Maritimes, les Bouches-du-Rhône, le Var et le Vaucluse. Elle est créée sous le nom de Provence-Côte d'Azur-Corse en 1960. Elle devient Provence-Côte d'Azur à la suite de la constitution de la région Corse en 1970 puis est rebaptisée Provence-Alpes-Côte d'Azur en 19764. Depuis 2018, le conseil régional utilise le nom « région Sud Provence-Alpes-Côte-d'Azur » (région Sud en abrégé) sur ses documents de communication, bien que le nom officiel de la région reste inchangé.", "/images/logo/provence-alpes-côte-d'azur.jpg", "images/Provence-Alpes-Côte-d'Azur/provence-alpe-côte-d'azur.jpg", "images/Provence-Alpes-Côte-d'Azur/provence-alpes-cote-d-azur-departement.png")));
            Assert.True(Mgr.Regions[0].Lieux[0].Equals(new Lieu("le Panoramique des Dômes", "Le plus haut volcan de la Chaîne des Puys-faille de Limagne, haut lieu tectonique inscrit au Patrimoine Mondial de l’UNESCO depuis le 2 juillet 2018. En 15 minutes, le Panoramique des Dômes vous emmène au sommet du puy de Dôme pour une découverte à 360° des volcans endormis de la Chaîne des Puys et de la Faille de Limagne, cet ensemble géologique témoin de la rupture des continents, unique au monde.", "/images/Auvergne-Rhone-Alpe/Lieux/Panoramique_des_Dômes1.jpg", "/images/Auvergne-Rhone-Alpe/Lieux/Panoramique_des_Dômes2.jpg", "/images/Auvergne-Rhone-Alpe/Lieux/Panoramique_des_Dômes3.png", new Region("Auvergne-Rhône-Alpes", "Auvergne-Rhône-Alpes est une région administrative française située dans la partie centrale et orientale du sud de la France. Elle a été créée par la réforme territoriale de 2015 et mise en place après les élections régionales de décembre 2015. Regroupant les anciennes régions Auvergne et Rhône-Alpes, elle se compose de 12 départements et d'une métropole à statut de collectivité territoriale, sa superficie est de 69 711 km2 et sa population s'élevait à 7 877 698 habitants8 en 2015 ; son chef-lieu est Lyon.", "/images/logo/auvergne-rhone-alpe3.jpg", "/images/Auvergne-Rhone-Alpe/Auvergne-Rhone-Alpes.jpg", "/images/Auvergne-Rhone-Alpe/auvergne-rhone-alpes-region-departements.jpg"))));
            Assert.True(Mgr.Regions[0].Specialites[0].Equals(new Specialite("Les ravioles", "Attention à ne pas confondre ravioles et raviolis, surtout face à un Drômois un peu sur les nerfs ! Il te dira que cette spécialité est produite à Romans-Sur-Isère et non en Italie, que sa pâte est extrêmement fine et que sa farce est préparée à base d’un Comté finement affiné. En tout cas, on le rejoint sur le fait que les ravioles sont un délice !", "images/Auvergne-Rhone-Alpe/specialite/raviole.jpg", "images/Auvergne-Rhone-Alpe/specialite/raviole2.jpeg", new Region("Auvergne-Rhône-Alpes", "Auvergne-Rhône-Alpes est une région administrative française située dans la partie centrale et orientale du sud de la France. Elle a été créée par la réforme territoriale de 2015 et mise en place après les élections régionales de décembre 2015. Regroupant les anciennes régions Auvergne et Rhône-Alpes, elle se compose de 12 départements et d'une métropole à statut de collectivité territoriale, sa superficie est de 69 711 km2 et sa population s'élevait à 7 877 698 habitants8 en 2015 ; son chef-lieu est Lyon.", "/images/logo/auvergne-rhone-alpe3.jpg", "/images/Auvergne-Rhone-Alpe/Auvergne-Rhone-Alpes.jpg", "/images/Auvergne-Rhone-Alpe/auvergne-rhone-alpes-region-departements.jpg"))));
            Assert.True(Mgr.Regions[0].Objets[0].Equals(new Objet("Briquet Dupont", "A quoi reconnaît-on le briquet Dupont ? Sans nul doute à une simple note, un la, qui résonne dès que la flemme apparaît. Exportés partout dans le monde, ces briquets sont créés depuis 145 ans à Faverges, en Haute-Savoie, dans une entreprise de 180 salariés. Si la partie usinage s'est largement automatisée, de nombreux postes restent manuels pour effectuer des gestes précis et délicats. Il s'agit notamment d'appliquer une laque d'excellente qualité, exportée d'Asie depuis 3000 ans, sur un support métallique. Et à chaque étape, un contrôle technique est réalité. Si le briquet présente le moindre défaut non rectifiable, il repart à l'usinage. Derrière chaque briquet Dupont se cache ainsi une centaine d'heures de travail. Environ 25 000 pièces sortent ainsi chaque année du site de Faverges.", "images/Auvergne-Rhone-Alpe/Objets/briquet.jpg", "images/Auvergne-Rhone-Alpe/Objets/briquet2.jpg", new Region("Auvergne-Rhône-Alpes", "Auvergne-Rhône-Alpes est une région administrative française située dans la partie centrale et orientale du sud de la France. Elle a été créée par la réforme territoriale de 2015 et mise en place après les élections régionales de décembre 2015. Regroupant les anciennes régions Auvergne et Rhône-Alpes, elle se compose de 12 départements et d'une métropole à statut de collectivité territoriale, sa superficie est de 69 711 km2 et sa population s'élevait à 7 877 698 habitants8 en 2015 ; son chef-lieu est Lyon.", "/images/logo/auvergne-rhone-alpe3.jpg", "/images/Auvergne-Rhone-Alpe/Auvergne-Rhone-Alpes.jpg", "/images/Auvergne-Rhone-Alpe/auvergne-rhone-alpes-region-departements.jpg"))));
            
            Assert.True(Mgr.Regions[0].Lieux[0].Activites[0].Equals(new Activite("Parapente")));
            Assert.True(Mgr.Regions[0].Lieux[0].Avis[0].Equals(new Avis(new Utilisateur("DEVAUX", "Patrick", "patrick.jpg", 56, "batrick.DEVAUX@gmail.com", "06 23 45 61 89", "Bonjour, comme vous l'avez vu je m'appelle batrick, j'ai deux enfant et je suis blombier.", "PatPat", "Patrick78"), "Ce lieu est magnifique")));
            
            Assert.True(Mgr.Regions[0].Specialites[1].Specialites[0].Equals(new Specialite("Les ravioles", "Attention à ne pas confondre ravioles et raviolis, surtout face à un Drômois un peu sur les nerfs ! Il te dira que cette spécialité est produite à Romans-Sur-Isère et non en Italie, que sa pâte est extrêmement fine et que sa farce est préparée à base d’un Comté finement affiné. En tout cas, on le rejoint sur le fait que les ravioles sont un délice !", "images/Auvergne-Rhone-Alpe/specialite/raviole.jpg", "images/Auvergne-Rhone-Alpe/specialite/raviole2.jpeg", new Region("Auvergne-Rhône-Alpes", "Auvergne-Rhône-Alpes est une région administrative française située dans la partie centrale et orientale du sud de la France. Elle a été créée par la réforme territoriale de 2015 et mise en place après les élections régionales de décembre 2015. Regroupant les anciennes régions Auvergne et Rhône-Alpes, elle se compose de 12 départements et d'une métropole à statut de collectivité territoriale, sa superficie est de 69 711 km2 et sa population s'élevait à 7 877 698 habitants8 en 2015 ; son chef-lieu est Lyon.", "/images/logo/auvergne-rhone-alpe3.jpg", "/images/Auvergne-Rhone-Alpe/Auvergne-Rhone-Alpes.jpg", "/images/Auvergne-Rhone-Alpe/auvergne-rhone-alpes-region-departements.jpg"))));
            Assert.True(Mgr.Regions[0].Specialites[0].Lieux[0].Equals(new Lieu("le Panoramique des Dômes", "Le plus haut volcan de la Chaîne des Puys-faille de Limagne, haut lieu tectonique inscrit au Patrimoine Mondial de l’UNESCO depuis le 2 juillet 2018. En 15 minutes, le Panoramique des Dômes vous emmène au sommet du puy de Dôme pour une découverte à 360° des volcans endormis de la Chaîne des Puys et de la Faille de Limagne, cet ensemble géologique témoin de la rupture des continents, unique au monde.", "/images/Auvergne-Rhone-Alpe/Lieux/Panoramique_des_Dômes1.jpg", "/images/Auvergne-Rhone-Alpe/Lieux/Panoramique_des_Dômes2.jpg", "/images/Auvergne-Rhone-Alpe/Lieux/Panoramique_des_Dômes3.png", new Region("Auvergne-Rhône-Alpes", "Auvergne-Rhône-Alpes est une région administrative française située dans la partie centrale et orientale du sud de la France. Elle a été créée par la réforme territoriale de 2015 et mise en place après les élections régionales de décembre 2015. Regroupant les anciennes régions Auvergne et Rhône-Alpes, elle se compose de 12 départements et d'une métropole à statut de collectivité territoriale, sa superficie est de 69 711 km2 et sa population s'élevait à 7 877 698 habitants8 en 2015 ; son chef-lieu est Lyon.", "/images/logo/auvergne-rhone-alpe3.jpg", "/images/Auvergne-Rhone-Alpe/Auvergne-Rhone-Alpes.jpg", "/images/Auvergne-Rhone-Alpe/auvergne-rhone-alpes-region-departements.jpg"))));
            Assert.True(Mgr.Regions[0].Specialites[0].Avis[0].Equals(new Avis(new Utilisateur("DEVAUX", "Patrick", "patrick.jpg", 56, "batrick.DEVAUX@gmail.com", "06 23 45 61 89", "Bonjour, comme vous l'avez vu je m'appelle batrick, j'ai deux enfant et je suis blombier.", "PatPat", "Patrick78"), "Cette recette est délicieuse")));

            Assert.True(Mgr.Regions[0].Objets[1].Objets[0].Equals(new Objet("Briquet Dupont", "A quoi reconnaît-on le briquet Dupont ? Sans nul doute à une simple note, un la, qui résonne dès que la flemme apparaît. Exportés partout dans le monde, ces briquets sont créés depuis 145 ans à Faverges, en Haute-Savoie, dans une entreprise de 180 salariés. Si la partie usinage s'est largement automatisée, de nombreux postes restent manuels pour effectuer des gestes précis et délicats. Il s'agit notamment d'appliquer une laque d'excellente qualité, exportée d'Asie depuis 3000 ans, sur un support métallique. Et à chaque étape, un contrôle technique est réalité. Si le briquet présente le moindre défaut non rectifiable, il repart à l'usinage. Derrière chaque briquet Dupont se cache ainsi une centaine d'heures de travail. Environ 25 000 pièces sortent ainsi chaque année du site de Faverges.", "images/Auvergne-Rhone-Alpe/Objets/briquet.jpg", "images/Auvergne-Rhone-Alpe/Objets/briquet2.jpg", new Region("Auvergne-Rhône-Alpes", "Auvergne-Rhône-Alpes est une région administrative française située dans la partie centrale et orientale du sud de la France. Elle a été créée par la réforme territoriale de 2015 et mise en place après les élections régionales de décembre 2015. Regroupant les anciennes régions Auvergne et Rhône-Alpes, elle se compose de 12 départements et d'une métropole à statut de collectivité territoriale, sa superficie est de 69 711 km2 et sa population s'élevait à 7 877 698 habitants8 en 2015 ; son chef-lieu est Lyon.", "/images/logo/auvergne-rhone-alpe3.jpg", "/images/Auvergne-Rhone-Alpe/Auvergne-Rhone-Alpes.jpg", "/images/Auvergne-Rhone-Alpe/auvergne-rhone-alpes-region-departements.jpg"))));
            Assert.True(Mgr.Regions[0].Objets[0].Lieux[0].Equals(new Lieu("le Panoramique des Dômes", "Le plus haut volcan de la Chaîne des Puys-faille de Limagne, haut lieu tectonique inscrit au Patrimoine Mondial de l’UNESCO depuis le 2 juillet 2018. En 15 minutes, le Panoramique des Dômes vous emmène au sommet du puy de Dôme pour une découverte à 360° des volcans endormis de la Chaîne des Puys et de la Faille de Limagne, cet ensemble géologique témoin de la rupture des continents, unique au monde.", "/images/Auvergne-Rhone-Alpe/Lieux/Panoramique_des_Dômes1.jpg", "/images/Auvergne-Rhone-Alpe/Lieux/Panoramique_des_Dômes2.jpg", "/images/Auvergne-Rhone-Alpe/Lieux/Panoramique_des_Dômes3.png", new Region("Auvergne-Rhône-Alpes", "Auvergne-Rhône-Alpes est une région administrative française située dans la partie centrale et orientale du sud de la France. Elle a été créée par la réforme territoriale de 2015 et mise en place après les élections régionales de décembre 2015. Regroupant les anciennes régions Auvergne et Rhône-Alpes, elle se compose de 12 départements et d'une métropole à statut de collectivité territoriale, sa superficie est de 69 711 km2 et sa population s'élevait à 7 877 698 habitants8 en 2015 ; son chef-lieu est Lyon.", "/images/logo/auvergne-rhone-alpe3.jpg", "/images/Auvergne-Rhone-Alpe/Auvergne-Rhone-Alpes.jpg", "/images/Auvergne-Rhone-Alpe/auvergne-rhone-alpes-region-departements.jpg"))));
            Assert.True(Mgr.Regions[0].Objets[0].Avis[0].Equals(new Avis(new Utilisateur("DEVAUX", "Patrick", "patrick.jpg", 56, "batrick.DEVAUX@gmail.com", "06 23 45 61 89", "Bonjour, comme vous l'avez vu je m'appelle batrick, j'ai deux enfant et je suis blombier.", "PatPat", "Patrick78"), "Cet objet est très joli")));

        }
    }
}
